/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2019-05-12 08:40:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class editsheetdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      conn.Conn connDB = null;
      connDB = (conn.Conn) _jspx_page_context.getAttribute("connDB", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (connDB == null){
        connDB = new conn.Conn();
        _jspx_page_context.setAttribute("connDB", connDB, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      conn.Conn connDB1 = null;
      connDB1 = (conn.Conn) _jspx_page_context.getAttribute("connDB1", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (connDB1 == null){
        connDB1 = new conn.Conn();
        _jspx_page_context.setAttribute("connDB1", connDB1, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      conn.Conn connDB2 = null;
      connDB2 = (conn.Conn) _jspx_page_context.getAttribute("connDB2", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (connDB2 == null){
        connDB2 = new conn.Conn();
        _jspx_page_context.setAttribute("connDB2", connDB2, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      conn.Conn connDB3 = null;
      connDB3 = (conn.Conn) _jspx_page_context.getAttribute("connDB3", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (connDB3 == null){
        connDB3 = new conn.Conn();
        _jspx_page_context.setAttribute("connDB3", connDB3, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

  request.setCharacterEncoding("UTF-8");
  String username=(String)session.getAttribute("username");
  String sheetid=request.getParameter("sheetid");
  String sheetname=request.getParameter("sheetname");
  String picture=request.getParameter("file");
  String introduction=request.getParameter("introduction");
  String[] tagname=request.getParameterValues("tag");
  String strSql="";
  String userid="";
  if(username!="")
		strSql="select userid from Users where username='"+username+"'"; 
	ResultSet rs=connDB.executeQuery(strSql);//查询
	while(rs.next())
		userid=rs.getString("userid");
	try{
  String str = "update Sheet set name='"+sheetname+"',introduction='"+introduction+"',picture='"+picture+"' where userid='"+userid+"' and id='"+sheetid+"'";
int t = connDB.executeUpdate(str);
  if (t == 0) {

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  alert(\"保存失败\");\r\n");
      out.write("  history.back();\r\n");
      out.write("</script>\r\n");
 } else {
	
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t    alert(\"保存成功\");\r\n");
      out.write("\t    history.back();\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

}
} catch (Exception e) {
  System.out.println(e.getMessage());
}
	try{
		String str="delete from SheetTag where sheetid='"+sheetid+"'";
		int t = connDB.executeUpdate(str);
	}catch (Exception e) {
		  System.out.println(e.getMessage());
	}
	int length=tagname.length;
	int i=0;
	if(i<length&&i<3){
			request.setCharacterEncoding("UTF-8");
			String strSql1="";
			if(tagname[i]!="")
				strSql1="select id from Tag where name='"+tagname[i]+"'"; 
			try{
			ResultSet rs1=connDB1.executeQuery(strSql1);//查询
			while(rs1.next()){
				String tagid=rs1.getString("id");
				try{
					String str = "insert into SheetTag values('"+Integer.valueOf(sheetid)+"','"+Integer.valueOf(tagid)+"')";
					int t = connDB1.executeUpdate(str);
					  if (t == 0) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t  alert(\"保存失败\");\r\n");
      out.write("\t\t\t\t\t  history.back();\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t");
 } else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t    alert(\"保存成功\");\r\n");
      out.write("\t\t\t\t\t\t    history.back();\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t");

					}
					} catch (Exception e) {
					  System.out.println(e.getMessage());
					}
			}} catch (Exception e) {
				  System.out.println(e.getMessage());
				}
		}
			i++;
			if(i<length&&i<3){
				request.setCharacterEncoding("UTF-8");
				String strSql2="";
				if(tagname[i]!="")
					strSql2="select id from Tag where name='"+tagname[i]+"'"; 
				try{
				ResultSet rs2=connDB2.executeQuery(strSql2);//查询
				while(rs2.next()){
					String tagid=rs2.getString("id");
					try{
						String str = "insert into SheetTag values('"+Integer.valueOf(sheetid)+"','"+Integer.valueOf(tagid)+"')";
						int t = connDB2.executeUpdate(str);
						  if (t == 0) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t  alert(\"保存失败\");\r\n");
      out.write("\t\t\t\t\t\t  history.back();\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t");
 } else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t    alert(\"保存成功\");\r\n");
      out.write("\t\t\t\t\t\t\t    history.back();\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");

						}
						} catch (Exception e) {
						  System.out.println(e.getMessage());
						}
				}} catch (Exception e) {
					  System.out.println(e.getMessage());
					}
			}
			i++;
			if(i<length&&i<3){
				request.setCharacterEncoding("UTF-8");
				String strSql3="";
				if(tagname[i]!="")
					strSql3="select id from Tag where name='"+tagname[i]+"'"; 
				try{
				ResultSet rs3=connDB3.executeQuery(strSql3);//查询
				while(rs3.next()){
					String tagid=rs3.getString("id");
					try{
						String str = "insert into SheetTag values('"+Integer.valueOf(sheetid)+"','"+Integer.valueOf(tagid)+"')";
						int t = connDB3.executeUpdate(str);
						  if (t == 0) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t  alert(\"保存失败\");\r\n");
      out.write("\t\t\t\t\t\t  history.back();\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t");
 } else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t    alert(\"保存成功\");\r\n");
      out.write("\t\t\t\t\t\t\t    history.back();\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t");

						}
						} catch (Exception e) {
						  System.out.println(e.getMessage());
						}
				}} catch (Exception e) {
					  System.out.println(e.getMessage());
					}
			}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
