/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2019-04-23 06:50:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("    function check(theform){\t\t\r\n");
      out.write("\t\tif(theform.username.value==\"\"){\r\n");
      out.write("\t\t   alert(\"用户名不能为空！\");\r\n");
      out.write("\t\t   theform.username.focus();\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t if(theform.userpwd.value==\"\"){\r\n");
      out.write("\t\t   alert(\"密码不能为空！\");\r\n");
      out.write("\t\t   theform.userpwd.focus();\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t    if(theform.userpwd.value!=theform.userpwd1.value){\r\n");
      out.write("\t       alert(\"两次密码不一致，请重新输入！\");\r\n");
      out.write("\t       theform.userpwd2.value=\"\";\r\n");
      out.write("\t       theform.userpwd2.focus();\r\n");
      out.write("\t       return false;\r\n");
      out.write("\t    }\r\n");
      out.write("            if(theform.mail.value==\"\"){\r\n");
      out.write("\t\t   alert(\"邮箱不能为空！\");\r\n");
      out.write("\t\t   theform.mail.focus();\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("            }\r\n");
      out.write("\t}\r\n");
      out.write("    function checkAddress() {    \r\n");
      out.write("        var reg =  /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(\\.[a-zA-Z0-9_-])+/;    \r\n");
      out.write("        if(!reg.test(document.form1.mail.value)){\r\n");
      out.write("\t       alert(\"请填写正确的邮箱格式！\");\r\n");
      out.write("           document.form1.mail.value=\"\";\r\n");
      out.write("\t       document.form1.mail.focus();\r\n");
      out.write("\t       return false;\r\n");
      out.write("\t    }\r\n");
      out.write("    }\r\n");
      out.write("    function checkDate() {    \r\n");
      out.write("        var reg = /^\\d{4}(\\-|\\/|\\.)\\d{1,2}\\1\\d{1,2}$/ ;    \r\n");
      out.write("        if(!reg.test(document.form1.birthday.value)){\r\n");
      out.write("\t       alert(\"请填写正确的日期格式！\");\r\n");
      out.write("           document.form1.birthday.value=\"\";\r\n");
      out.write("\t       document.form1.birthday.focus();\r\n");
      out.write("\t       return false;\r\n");
      out.write("\t    }\r\n");
      out.write("    }\r\n");
      out.write(" </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("<h2 style=\"color:red\">用户注册</h2>\r\n");
      out.write("<hr width=\"60%\">\r\n");
      out.write("<form name=\"form1\" action=\"doRegister.jsp\" method=\"post\" onSubmit=\"return check(this)\">\r\n");
      out.write("<table border=\"0\" align=\"center\">\r\n");
      out.write("  <tr>\r\n");
      out.write("   <td width=\"80\">用&nbsp;户&nbsp;名</td>\r\n");
      out.write("   <td width=\"226\"><input type=\"text\" name=\"username\">*</td></tr>\r\n");
      out.write("<tr><td>密&nbsp;&nbsp;码&nbsp;&nbsp;</td>\r\n");
      out.write("   <td><input type=\"password\" name=\"userpwd\">*</td></tr>\r\n");
      out.write("<tr><td>密码确认</td>\r\n");
      out.write("   <td><input type=\"password\" name=\"userpwd1\">*</td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("   <td>性&nbsp;&nbsp;别&nbsp;&nbsp;</td>\r\n");
      out.write("   <td><input type=\"radio\" name=\"sex\" checked value=\"男\">男\r\n");
      out.write("       <input type=\"radio\" name=\"sex\">女\r\n");
      out.write("   </td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("   <td>出生年月</td>\r\n");
      out.write("   <td><input type=\"text\" name=\"birthday\" onBlur=\"checkDate()\"></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("   <td>邮&nbsp;&nbsp;箱&nbsp;&nbsp;</td>\r\n");
      out.write("   <td><input type=\"text\" name=\"mail\" onBlur=\"checkAddress()\"></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("   <td>联系方式</td>\r\n");
      out.write("   <td><input type=\"text\" name=\"phonenum\"></td></tr>\r\n");
      out.write("<tr>\r\n");
      out.write("   <td colspan=\"2\" align=\"center\">\r\n");
      out.write("      <input type=\"submit\" value=\"提交\">\r\n");
      out.write("      &nbsp;&nbsp;&nbsp;\r\n");
      out.write("      <input type=\"reset\" value=\"清除\">\r\n");
      out.write("   </td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
